version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./Docker/python/Dockerfile
    volumes:
      - ./src:/usr/src/app
    secrets:
      - POSTGRES_PASSWORD
    ports:
      - 8000:8000
    command: [ "python", "main.py" ]
    restart: always

  postgres:
    image: postgres:14.0
    environment:
      POSTGRES_USER: yowayowa
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_DB: "pg"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    container_name: spajam2022-postgres-db
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    secrets:
      - POSTGRES_PASSWORD

secrets:
  POSTGRES_PASSWORD:
    file: ./postgresql/secrets/password.txt