version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./Docker/python/Dockerfile
    volumes:
      - ./src:/usr/src/app
      - ./scripts:/usr/scripts
    secrets:
      - POSTGRES_PASSWORD
    ports:
      - 8000:8000
    command:
      [
        "/usr/scripts/wait-for-it.sh",
        "--timeout=90",
        "--strict",
        " postgres:5432",
        "--",
        "python",
        "main.py"
      ]
    restart: always

  postgres:
    image: postgres:14.0
    environment:
      POSTGRES_USER: yowayowa
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_DB: "pg"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    container_name: spajam2022-postgres-db
    volumes:
      - ./Docker/postgres/initdb:/docker-entrypoint-initdb.d
      - ./db/postgres:/var/lib/postgresql/data
    secrets:
      - POSTGRES_PASSWORD

secrets:
  POSTGRES_PASSWORD:
    file: ./secrets/password.txt
